### ISSUE TITLE
CustomLogin sample does not work

### ISSUE THREAD

**Issue by Lonli-Lokli** [okta/samples-js-angular#134]
I run in root folder
- npm run install
- npm run build:custom-page

Got this error on second step
Node v14.18.2, npm 6.14.15
```
Error: node_modules/@okta/okta-auth-js/lib/idx/remediators/EnrollPoll.d.ts:23:5 - error TS2416: Property 'getValuesAfterProceed' in type 'EnrollPoll' is not assignable to the same property 
in base type 'Remediator'.
  Type '() => unknown' is not assignable to type '() => RemediationValues'.
    Type 'unknown' is not assignable to type 'RemediationValues'.

23     getValuesAfterProceed(): unknown;
```

**Comment by aarongranick-okta** [comment]
@Lonli-Lokli Thanks for reporting this. We will investigate and get this fixed

**Comment by aarongranick-okta** [comment]
I have found a workaround which is to put
```
"strictNullChecks": false,
```
in the compilerOptions section of your tsconfig.json file

**Comment by aarongranick-okta** [comment]
@Lonli-Lokli `@okta/okta-auth-js` version 5.10.1 has been released with this fix. If you clear the `package-lock.json` file and run `npm install` again, it should install this version with the fix.
