### ISSUE TITLE
URL passed to constructor contains "-admin" in subdomain

### ISSUE THREAD

**Issue by kcferguson1** [okta/samples-js-angular#20]
getting this error when trying to run on localhost:8080

"URL passed to constructor contains "-admin" in subdomain. Required usage: new OktaAuth({url: "https://dev-12345.okta.com})"

**Comment by Shisyr** [comment]
How to solve this problem?

**Comment by mraible** [comment]
Remove -admin from your URL. The issuer URL you should use is at API > Authorization Servers.
