### ISSUE TITLE
Prod build doesn't render correctly

### ISSUE THREAD

**Issue by GarettRogers** [okta/samples-js-angular#37]
Trying to do a prod build of okta-hosted-login, and the compiled project doesn't appear to work. I am getting this error when I try to view the page in the browser:

`Uncaught TypeError: Cannot use 'in' operator to search for 'window' in undefined`

Doing `ng serve` works without issue.

**Comment by swiftone** [comment]
Recent versions of the angular SDK have addressed problems with AOT compilation.  We're not aware of any remaining complications regarding that SDK nor this sample.
