### ISSUE TITLE
Samples won't build using enableIvy: true

### ISSUE THREAD

**Issue by dancurrotto** [okta/samples-js-angular#41]
Editing the tsconfig.json setting angularCompilerOptions enableIvy to true:

{
  "compileOnSave": false,
  "angularCompilerOptions": {
    "enableIvy": true
  },
  "compilerOptions": {
    "importHelpers": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "module": "esnext",
    "baseUrl": "./"
  }
}

Then runing ng build --prod or ng serve -o results in the following:

ERROR in There is no format with import statements in 'C:/Users/dcurrotto/source/repos/samples-js-angular/custom-login/node_modules/@okta/okta-angular' entry-point.

**Comment by swiftone** [comment]
As of our 1.3.1 release (https://github.com/okta/okta-oidc-js/releases/tag/%40okta%2Fokta-angular%401.3.1 ), we are unaware of any issues with ivy and/or AOT compilation.

If anyone encounters new problems, please feel free to open a new issue with details.
