### ISSUE TITLE
There was an unexpected internal error. Please try again. after successful login 

### ISSUE THREAD

**Issue by spirit-catcher** [okta/samples-js-angular#56]
THis is an issue reported but not followed up on by another user in Oct 2019.

Pulled the project installed it with npm, configured it for my OKTA environment. Everything starts fine and the login page is rendered properly. The user is authenticated and it shows in the logs on the OKTA server that the user was successful. But then the application it pops an error saying There was an unexpected internal error. Please try again. and leaves me at the login page.

I have this very same issue.

Mar 01 12:38:23	Raymond Walker  (User)	User accessing Okta admin appsuccess	Raymond Walker  (AppUser)
This shows I am successfully logging in to OKTA but my Website login box returns with There was an unexpected internal error. Please try again.

ANy Ideas on what could be the cause

**Comment by swiftone** [comment]
@spirit-catcher - Thanks for the bug report.  Unfortunately we're unable to replicate your bug based on the information provided.

- What versions of `okta-angular` and `okta-auth-js` are in your `node_modules/`?
- Are you using the `okta-hosted-login` or `custom-login` directory?
- Do you see which network calls are giving you an error code in your browser devtools?

**Comment by swiftone** [comment]
Closing ticket as not reproducible.  Feel free to reopen with more details!
