### ISSUE TITLE
Where is process.env being set

### ISSUE THREAD

**Issue by amazonotter** [okta/samples-js-angular#60]
Hi,

Any ideas where process.env is being created and set?  I'm referring to the app.config.ts file.  

ng serve does not work.  I get an error: 

An unhandled exception occurred: Environment variable ISSUER must be set.

**Comment by swiftone** [comment]
Hi @amazonotter - See the README file in the opening paragraphs where it describes setting the Client Id and Issuer, and mentions the `testenv` file.

**Comment by amazonotter** [comment]
Thank you for the response.

I've read the README.MD file as well as the dotenv npm link.

Could you kindly tell me what I'm still doing wrong, I've placed a testenv.env file at the root of the "custom-login" folder with the following:
CLIENT_ID=123456xxxx
ISSUER=https://my123456xxxx-admin.okta.com/oauth2/default
OKTA_TESTING_DISABLEHTTPSCHECK=true

And I placed "require('dotenv').config();" in my app.modules.ts file as well.

And then when I do my "ng serve" I get this error:
"An unhandled exception occurred: Environment variable ISSUER must be set. "

**Comment by tharun-debug** [comment]
hi @amazonotter  did you solve that issue i am facing the same issue where to save the testenv file

**Comment by swiftone** [comment]
@amazonotter , @tharun-debug: Try using `testenv` (no .env extension), and put it at the same directory as the readme, one level ABOVE `custom-login`.

**Comment by swiftone** [comment]
Closing as stale and presumably fixed.  If this continues to be an issue feel free to reopen with details if there continues to be a problem.
