### ISSUE TITLE
404 error - page can't be found "implicit/callback"

### ISSUE THREAD

**Issue by harshamaram** [okta/samples-js-angular#64]
I did not touch any part of the given code from "Okta-Hosted Login".
When ran the project with "ng serve", its all working fine.

But when generated distribution files, functionality broken and see the following issue after authentication from Okta page:

No webpage was found for the web address: http://localhost:8080/implicit/callback?code=103QSC6F_NOnVKh01pzr&state=NNDoqOHGt7iZpidooLWz7s72L4qcyJVF29E3N0isRuQnF400zHohXepOQBA0dy0b

-------------------------------------

Steps to reproduce:
Clone "https://github.com/okta/samples-js-angular/tree/master/okta-hosted-login"
Set the environment variables as given in the README.

build using - 
ng build

start application with -
http-server dist

-------------------------------------

Following are my application settings on Okta:
Application type : Single Page App (SPA)
Authorization Code - YES
Implicit - NO

Login redirect URIs: http://localhost:8080/implicit/callback  
Logout redirect URIs: http://localhost:8080  
Login initiated by: App Only

Initiate login URI : http://localhost:8080/implicit/callback
Client authentication: Use PKCE (for public clients)

**Comment by mraible** [comment]
`http-server` won't work for SPA that expect all 404s to go to index.html. I'd recommend using [http-server-spa](https://www.npmjs.com/package/http-server-spa) instead.

**Comment by harshamaram** [comment]
Thanks mraible 
Its working.
