### ISSUE TITLE
E401 - Unable to authenticate when running npm install

### ISSUE THREAD

**Issue by stujfiter** [okta/samples-js-angular#71]
I am trying to get the sample angular app to run on my macOS (10.15.4) and am receiving the following error when attempting to run `npm install`
```
➜  samples-js-angular git:(master) npm install
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="Artifactory Realm"
```

I was able to work around the issue by running `npm install --registry https://registry.npmjs.org`, per the recommendation from [https://github.com/zowe/zowe-cli/issues/377](https://github.com/zowe/zowe-cli/issues/377)  but still wanted to raise the issue incase others run into the same.

[2020-05-21T19_09_42_802Z-debug.log](https://github.com/okta/samples-js-angular/files/4664299/2020-05-21T19_09_42_802Z-debug.log)

**Comment by swiftone** [comment]
@stujfiter - I believe this is related to your local configuration, perhaps a .npmrc file at your home dir or other path that modifies the default registry.

**Comment by stujfiter** [comment]
@swiftone That was it.  I had an .npmrc file in my home directory pointing at my corporate Artifactory registry.

Thank You
